if(NOT DEFINED STAGE)
  message(FATAL_ERROR "usage: cmake -DSTAGE=<submission-directory> -P scripts/check_size.cmake")
endif()
file(GLOB_RECURSE FILES LIST_DIRECTORIES false "${STAGE}/*")
set(TOTAL 0)
foreach(F IN LISTS FILES)
  file(SIZE "${F}" N)
  math(EXPR TOTAL "${TOTAL}+${N}")
endforeach()
math(EXPR REMAIN "1474560-${TOTAL}")
math(EXPR PCT "${TOTAL}*100/1474560")
message(STATUS "extracted bytes: ${TOTAL}; remaining: ${REMAIN}; used: ${PCT}%")
if(TOTAL GREATER 1474560)
  message(FATAL_ERROR "submission exceeds 1,474,560 bytes")
elseif(TOTAL GREATER 1350000)
  message(WARNING "submission exceeds the 1,350,000-byte safety target")
endif()
