if(NOT DEFINED EXECUTABLE OR NOT EXISTS "${EXECUTABLE}")
  message(FATAL_ERROR "usage: cmake -DEXECUTABLE=<game-binary> -DOUTPUT=<directory> -P scripts/package.cmake")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "" OR OUTPUT STREQUAL "/")
  message(FATAL_ERROR "OUTPUT must be a dedicated package directory")
endif()
get_filename_component(EXECUTABLE "${EXECUTABLE}" ABSOLUTE)
get_filename_component(OUTPUT "${OUTPUT}" ABSOLUTE)
get_filename_component(NAME "${EXECUTABLE}" NAME)
set(STAGE "${OUTPUT}/submission")
file(REMOVE_RECURSE "${STAGE}")
file(MAKE_DIRECTORY "${STAGE}")
configure_file("${EXECUTABLE}" "${STAGE}/${NAME}" COPYONLY)
configure_file("${CMAKE_CURRENT_LIST_DIR}/../README.md" "${STAGE}/README.txt" COPYONLY)
execute_process(COMMAND "${CMAKE_COMMAND}" -DSTAGE=${STAGE} -P "${CMAKE_CURRENT_LIST_DIR}/check_size.cmake" RESULT_VARIABLE SIZE_RESULT)
if(NOT SIZE_RESULT EQUAL 0)
  message(FATAL_ERROR "size verification failed; archive was not produced")
endif()
file(REMOVE "${OUTPUT}/SongsFromBadSectors.zip")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${OUTPUT}/SongsFromBadSectors.zip" --format=zip "${NAME}" README.txt WORKING_DIRECTORY "${STAGE}" RESULT_VARIABLE ARCHIVE_RESULT)
if(NOT ARCHIVE_RESULT EQUAL 0)
  message(FATAL_ERROR "archive creation failed")
endif()
message(STATUS "package: ${OUTPUT}/SongsFromBadSectors.zip")
