#!/usr/bin/env python3
"""Generate src/levels_gen.h from levels/*.json.

The JSON files are the shared source of truth (compatible across all ports).
This bakes them into C structs so the shipped binary needs no JSON parser
and stays a single self-contained executable. Coordinate scaling and the
derived fields (laser endpoints, roamer initial heading, mine polarity)
replicate the original ObstacleManager / entity logic exactly.

Run from the v4 directory:  python3 tools/gen_levels.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LEVELS_DIR = os.path.join(ROOT, "levels")
OUT = os.path.join(ROOT, "src", "levels_gen.h")

# Stable file keys and metadata live in a reviewable campaign manifest.
with open(os.path.join(LEVELS_DIR, "campaign.json")) as fh:
    CAMPAIGN = json.load(fh)
ORDER = [(entry["key"], "%02d" % (i + 1)) for i, entry in enumerate(CAMPAIGN)]

COLOR = {"red": 0, "blue": 1, "yellow": 2, "green": 3}
OBTYPE = {"sweeper": 0, "pulse_ring": 1, "laser_gate": 2, "roamer": 3, "magnet_mine": 4}
LEGACY_SCALE = 540.0 / 1280.0


def str_hash(s):
    """Replicate JS: hash = ((hash<<5) - hash) + charCode, 32-bit signed."""
    h = 0
    for ch in s:
        h = ((h << 5) - h) + ord(ch)
        h &= 0xFFFFFFFF
    # to signed 32
    if h >= 0x80000000:
        h -= 0x100000000
    return h


def parse_color(hexstr):
    hexstr = (hexstr or "#0a0a1a").lstrip("#")
    if len(hexstr) == 3:
        hexstr = "".join(c * 2 for c in hexstr)
    return int(hexstr[:6], 16)


def f(x):
    s = "%g" % round(float(x), 4)
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit(check=False):
    assert len(CAMPAIGN) == 40, "Campaign must have 40 stages"
    assert len({e["key"] for e in CAMPAIGN}) == 40, "Duplicate campaign key"
    assert sorted(e["legacy_id"] for e in CAMPAIGN if e.get("legacy_id")) == list(range(1,26))
    out = []
    out.append("/* AUTO-GENERATED by tools/gen_levels.py from the level JSON files. Do not edit. */")
    out.append('#include "maglava.h"')
    out.append("")

    for idx, (base, _label) in enumerate(ORDER, start=1):
        with open(os.path.join(LEVELS_DIR, base + ".json")) as fh:
            d = json.load(fh)
        legacy = d.get("coordinateFormat", "1280px") != "540px"
        sx = LEGACY_SCALE if legacy else 1.0

        magnets = d["magnets"]
        assert 2 <= len(magnets) <= 64, base
        assert len(d.get("obstacles", [])) <= 64, base
        assert len({m["id"] for m in magnets}) == len(magnets), base
        assert all(16 <= m["x"] * sx <= 524 for m in magnets), base
        assert all(m["color"] in COLOR for m in magnets), base
        assert magnets[-1]["y"] == min(m["y"] for m in magnets), base
        idmap = {m["id"]: i for i, m in enumerate(magnets)}

        # magnets
        out.append("static const MagnetDef L%d_mag[] = {" % idx)
        for m in magnets:
            out.append("  {%s,%s,%d}," % (f(m["x"] * sx), f(m["y"]), COLOR[m["color"]]))
        out.append("};")

        # checkpoints -> resolve respawn magnet index
        cps = d.get("checkpoints", [])
        if cps:
            out.append("static const CheckpointDef L%d_cp[] = {" % idx)
            for c in cps:
                ri = idmap[c["respawnPlatformId"]]
                out.append("  {%s,%d}," % (f(c["y"]), ri))
            out.append("};")
            cp_ref = "L%d_cp" % idx
        else:
            cp_ref = "0"

        # obstacles
        obs = d.get("obstacles", [])
        if obs:
            out.append("static const ObstacleDef L%d_ob[] = {" % idx)
            for o in obs:
                t = OBTYPE[o["type"]]
                ox = float(o.get("x", 0)) * sx
                oy = float(o.get("y", 0))
                length = float(o.get("length", 0))
                speed = float(o.get("speed", 0))
                on_ms = float(o.get("onDuration", 0))
                off_ms = float(o.get("offDuration", 0))
                ex = ey = 0.0
                init_angle = 0.0
                polarity = 0
                if t == OBTYPE["laser_gate"]:
                    # endX = x + (length or 100)*scaleX ; endY = y
                    span = length if length else 100.0
                    ex = ox + span * sx
                    ey = oy
                    if on_ms == 0:
                        on_ms = 1200.0
                    if off_ms == 0:
                        off_ms = 5000.0
                elif t == OBTYPE["sweeper"]:
                    if length == 0:
                        length = 80.0
                    if speed == 0:
                        speed = 150.0
                elif t == OBTYPE["pulse_ring"]:
                    if speed == 0:
                        speed = 35.0
                elif t == OBTYPE["roamer"]:
                    if speed == 0:
                        speed = 50.0
                    h = str_hash(o["id"])
                    init_angle = float(abs(h) % 360)
                elif t == OBTYPE["magnet_mine"]:
                    # original randomizes; make deterministic from id hash
                    polarity = 1 if (abs(str_hash(o["id"])) % 2) else 0
                out.append(
                    "  {%d,%s,%s,%s,%s,%s,%s,%s,%s,%s,%d},"
                    % (t, f(ox), f(oy), f(length), f(ex), f(ey), f(speed),
                       f(on_ms), f(off_ms), f(init_angle), polarity)
                )
            out.append("};")
            ob_ref = "L%d_ob" % idx
        else:
            ob_ref = "0"

        d.setdefault("obstacles", obs)
        out.append("")

    # LEVELS table
    out.append("const LevelDef LEVELS[LEVEL_COUNT] = {")
    for idx, (base, _label) in enumerate(ORDER, start=1):
        with open(os.path.join(LEVELS_DIR, base + ".json")) as fh:
            d = json.load(fh)
        entry = CAMPAIGN[idx - 1]
        name = d["name"].replace('"', '\\"')
        bg = parse_color(d.get("background", {}).get("color"))
        ncp = len(d.get("checkpoints", []))
        nob = len(d.get("obstacles", []))
        nmag = len(d["magnets"])
        cp_ref = "L%d_cp" % idx if ncp else "0"
        ob_ref = "L%d_ob" % idx if nob else "0"
        out.append(
            '  {"%s","%s",%s,%d,%s,%s,%s,%s,0x%06xu, %d,L%d_mag, %d,%s, %d,%s},'
            % (name, base, json.dumps(entry["hint"]), entry.get("legacy_id", 0),
               {"none":"ANOM_NONE", "flashlight":"ANOM_FLASHLIGHT", "race":"ANOM_RACE", "roll":"ANOM_ROLL"}[entry.get("anomaly", "none")], f(d["parTime"]), f(d["lavaSpeed"]), f(d["lavaAcceleration"]),
               bg, nmag, idx, ncp, cp_ref, nob, ob_ref)
        )
    out.append("};")
    out.append("")

    out.append("const char *const LEVEL_LABELS[LEVEL_COUNT] = {")
    out.append("  " + ", ".join('"%s"' % lbl for _, lbl in ORDER))
    out.append("};")
    out.append("")

    content = "\n".join(out)
    if check:
        with open(OUT) as fh:
            if fh.read() != content:
                raise SystemExit("Stale level data: run python3 tools/gen_levels.py")
        print("Campaign data is valid and generated header is current")
        return
    with open(OUT, "w") as fh:
        fh.write(content)
    print("Wrote", OUT, "(%d bytes)" % os.path.getsize(OUT))


if __name__ == "__main__":
    emit("--check" in sys.argv)
