#!/usr/bin/env python3
"""Compile one UTF-8 catalog for all native platforms; reject incomplete formats."""
import json,re,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]
d=json.loads((root/'i18n/catalog.json').read_text())
quote=lambda s:json.dumps(s,ensure_ascii=False)
rows=d['strings']
fmt=re.compile(r'%(?:\d+\$)?[-+ #0]*\d*(?:\.\d+)?[a-zA-Z%]')
for key,values in rows.items():
 assert len(values)==7 and values[0]==key and all(values),key
 for v in values:assert fmt.findall(key)==fmt.findall(v),(key,v)
lines=['/* Generated by tools/gen_i18n.py; edit i18n/catalog.json. */',
 'static const char *const language_codes[]={'+','.join(map(quote,d['languages']))+'};',
 'static const char *const language_names[]={'+','.join(map(quote,d['names']))+'};',
 'static const char *const messages[][7]={']
for key in sorted(rows):lines.append('{'+','.join(map(quote,rows[key]))+'},')
lines.append('};')
characters=''.join(sorted(set(''.join(x for row in rows.values() for x in row)+''.join(d['names'])+'0123456789×←↑→↓')))
lines.append('static const char locale_characters[]='+quote(characters)+';')
result='\n'.join(lines)+'\n';out=root/'src/i18n_gen.h'
if '--check' in sys.argv:assert out.read_text()==result,'Regenerate localization header'
else:out.write_text(result)
print(f'{len(rows)} complete messages across seven languages; format signatures match.')
