from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = (root / 'assets/fonts/Barlow-Medium.ttf').read_bytes()
out = root / 'src/generated/font_data.h'
out.parent.mkdir(exist_ok=True)
out.write_text('/* Generated by tools/embed_font.py; Barlow, SIL OFL. */\nstatic const unsigned char hd_font_data[] = {\n' + '\n'.join(','.join(str(b) for b in data[i:i+24])+',' for i in range(0,len(data),24)) + '\n};\n')
