.PHONY: all run web desktop test playtest check package size clean
all web:
	npm run build
run:
	npm run dev
desktop:
	npm run desktop
test:
	npm test
playtest:
	npm run playtest
check:
	npm run check
package:
	npm run package
size:
	npm run size
clean:
	rm -rf dist release test-results playwright-report
