#!/usr/bin/env bash
#
# update-site-downloads.sh — point the promo site at the latest GitHub release.
#
#   ./scripts/update-site-downloads.sh              # latest release
#   ./scripts/update-site-downloads.sh v2026.07.25-a9f2462
#
# Rewrites the generated block in promo-site/src/data/releases.js with the real
# asset URLs, sizes and the tag. A script rather than a hand-edit because asset
# names carry the version, so "latest" cannot be expressed as a static URL and
# every release would otherwise need someone to remember to update the site.
#
set -euo pipefail
cd "$(dirname "$0")/.."

REPO="${REPO:-SweetPapa/FloppyJam}"
TAG="${1:-}"
OUT="promo-site/src/data/releases.js"

die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }
info() { printf '\033[36m==>\033[0m %s\n' "$*"; }

command -v gh >/dev/null || die "the GitHub CLI is not installed"
[ -n "$TAG" ] || TAG=$(gh release list -R "$REPO" --limit 1 --json tagName --jq '.[0].tagName')
[ -n "$TAG" ] || die "no releases on $REPO yet"
info "release $TAG"

gh release view "$TAG" -R "$REPO" --json tagName,publishedAt,assets \
  --jq '{tag: .tagName, published: .publishedAt, assets: [.assets[] | {name, size, url}]}' \
  > /tmp/.rel.json

python3 - "$TAG" "$REPO" "$OUT" <<'PY'
import json, sys, datetime
tag, repo, out = sys.argv[1], sys.argv[2], sys.argv[3]
d = json.load(open('/tmp/.rel.json'))
assets = {a['name']: a for a in d['assets']}

def pick(*suffixes):
    """First asset whose name ends with one of these, ignoring the unsigned raw exe."""
    for s in suffixes:
        for n, a in assets.items():
            if n.endswith(s) and n != 'breakpar.exe':
                return a
    return None

def mb(n):
    return f"{n/1024/1024:.2f} MB" if n >= 1024*1024 else f"{n//1024} KB"

win = pick('-windows-x64.zip', '-windows-x64.exe')
mac = pick('-macos.dmg', '-macos-universal.zip')
sums = assets.get('SHA256SUMS.txt')

if not win or not mac:
    print('error: could not find both a Windows and a macOS asset in', tag, file=sys.stderr)
    sys.exit(1)

body = f"""/* GENERATED by scripts/update-site-downloads.sh — do not hand-edit.
 *
 * Asset names carry the version, so "latest" cannot be written as a static URL.
 * Re-run the script after each release (or from the release workflow) and the
 * site follows.
 *
 * Release {tag}, published {d['published']}
 * Regenerated {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}
 */

export const REPO = 'https://github.com/{repo}'

export const latest = {{
  tag: '{tag}',
  notes: `${{REPO}}/releases/tag/{tag}`,
  checksums: {("'" + sums['url'] + "'") if sums else 'null'},
  windows: {{
    name: '{win['name']}',
    size: '{mb(win['size'])}',
    url: '{win['url']}',
  }},
  macos: {{
    name: '{mac['name']}',
    size: '{mb(mac['size'])}',
    url: '{mac['url']}',
  }},
}}
"""
open(out, 'w').write(body)
print(f"  windows  {win['name']}  {mb(win['size'])}")
print(f"  macos    {mac['name']}  {mb(mac['size'])}")
print(f"  -> {out}")
PY

rm -f /tmp/.rel.json
info "done — rebuild the site to pick it up (cd promo-site && npm run build)"
