#include "control.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
static void transition(ControlHarness*h,ControlState s){if(h->state!=s){h->state=s;h->transitions++;}}
void sfbs_control_init(ControlHarness*h,const char*seed){memset(h,0,sizeof*h);sfbs_seed_normalize(seed,h->seed);h->mode=MODE_FLOW;h->state=CTRL_TITLE;}
void sfbs_control_mode(ControlHarness*h,GameMode mode){if(mode<MODE_BLOOM||mode>MODE_PULSE)return;h->mode=mode;h->mode_mask|=1u<<mode;transition(h,CTRL_MODE_SELECT);}
void sfbs_control_start(ControlHarness*h){sfbs_game_init(&h->game,h->seed,h->mode);h->sample=0;transition(h,CTRL_PLAYING);}
void sfbs_control_pause(ControlHarness*h){if(h->state==CTRL_PLAYING)transition(h,CTRL_PAUSED);}
void sfbs_control_resume(ControlHarness*h){if(h->state==CTRL_PAUSED)transition(h,CTRL_PLAYING);}
void sfbs_control_step(ControlHarness*h,V2 input,bool pulse,uint32_t frames){if(h->state!=CTRL_PLAYING)return;uint64_t quantum=SFBS_RATE/60;for(uint32_t i=0;i<frames&&h->state==CTRL_PLAYING;i++){sfbs_game_step(&h->game,1.0f/60,input,pulse&&i==0,h->sample);h->sample+=quantum;if(h->game.ended)transition(h,CTRL_RESULTS);}}
void sfbs_control_restart(ControlHarness*h){if(h->state==CTRL_PAUSED||h->state==CTRL_RESULTS)sfbs_control_start(h);}
void sfbs_control_new_seed(ControlHarness*h,uint64_t entropy){sfbs_random_seed(entropy,h->seed);sfbs_control_start(h);}
void sfbs_control_title(ControlHarness*h){transition(h,CTRL_TITLE);}
static void check(ControlStatus*s,int ok,const char*name){s->checks++;if(!ok){s->failures++;if(!s->first_failure)s->first_failure=name;}}
static void hash(uint64_t*h,uint64_t x){*h^=x;*h*=1099511628211ULL;}
static uint64_t snapshot(const ControlHarness*h){uint64_t d=1469598103934665603ULL;int64_t px=(int64_t)lroundf(h->game.player.pos.x*1000),py=(int64_t)lroundf(h->game.player.pos.y*1000);hash(&d,h->state);hash(&d,h->sample);hash(&d,h->game.genome.master);hash(&d,h->game.phrase_index);hash(&d,h->game.integrity);hash(&d,h->game.recovered);hash(&d,(uint64_t)px);hash(&d,(uint64_t)py);return d;}
static void scripted(ControlHarness*h,int frames){for(int i=0;i<frames;i++){V2 in={(i/90)%2?.65f:-.4f,(i/120)%2?-.55f:.7f};sfbs_control_step(h,in,i%43==0,1);}}
ControlStatus sfbs_control_verify(void){ControlStatus s={0};s.digest=1469598103934665603ULL;for(int m=0;m<3;m++){GameMode mode=(GameMode)m;ControlHarness a,b;sfbs_control_init(&a,"CTRL77");sfbs_control_init(&b,"CTRL77");check(&s,a.state==CTRL_TITLE,"initial_title");sfbs_control_mode(&a,mode);sfbs_control_mode(&b,mode);check(&s,a.state==CTRL_MODE_SELECT&&a.mode==mode,"mode_select");sfbs_control_start(&a);sfbs_control_start(&b);check(&s,a.state==CTRL_PLAYING&&a.game.mode==mode,"start_playing");scripted(&a,240);scripted(&b,240);check(&s,snapshot(&a)==snapshot(&b),"scripted_input_determinism");uint64_t sample=a.sample;V2 pos=a.game.player.pos;sfbs_control_pause(&a);sfbs_control_step(&a,(V2){1,1},true,120);check(&s,a.state==CTRL_PAUSED&&a.sample==sample&&a.game.player.pos.x==pos.x&&a.game.player.pos.y==pos.y,"pause_freezes_state");sfbs_control_resume(&a);check(&s,a.state==CTRL_PLAYING,"resume_playing");a.game.freeze_echo=true;uint64_t end=sfbs_tick_sample((uint64_t)SFBS_BARS*4*SFBS_PPQN,a.game.genome.bpm);while(a.sample<=end+SFBS_RATE&&a.state==CTRL_PLAYING)sfbs_control_step(&a,(V2){.4f,-.25f},a.sample%(SFBS_RATE/2)<SFBS_RATE/60,1);check(&s,a.state==CTRL_RESULTS&&a.game.won,"results_after_full_run");uint64_t master=a.game.genome.master;sfbs_control_restart(&a);check(&s,a.state==CTRL_PLAYING&&a.game.genome.master==master&&a.sample==0,"same_seed_restart");if(mode!=MODE_BLOOM){while(!a.game.ended){a.game.player.invuln=0;sfbs_force_damage(&a.game);}sfbs_control_step(&a,(V2){0,0},false,1);check(&s,a.state==CTRL_RESULTS&&!a.game.won,"failure_results");}else{a.game.player.invuln=0;sfbs_force_damage(&a.game);check(&s,!a.game.ended,"bloom_survives_damage");}char old[7];memcpy(old,a.seed,7);sfbs_control_new_seed(&a,1234+m);check(&s,memcmp(old,a.seed,7)!=0&&a.state==CTRL_PLAYING,"new_seed_start");sfbs_control_title(&a);check(&s,a.state==CTRL_TITLE,"return_title");hash(&s.digest,snapshot(&a));s.modes_tested++;s.transitions_tested+=(int)a.transitions;}
 check(&s,s.modes_tested==3,"all_modes_toggled");return s;}
void sfbs_control_json(const ControlStatus*s){printf("{\"schema_version\":1,\"control_harness\":{\"state\":\"%s\",\"checks\":%d,\"failures\":%d,\"first_failure\":",s->failures?"failed":"passed",s->checks,s->failures);if(s->first_failure)printf("\"%s\"",s->first_failure);else printf("null");printf(",\"modes_tested\":%d,\"transitions_tested\":%d,\"bars_per_complete_run\":56,\"digest\":\"%016llx\"},\"ready\":%s}\n",s->modes_tested,s->transitions_tested,(unsigned long long)s->digest,s->failures?"false":"true");}
