#include "headless.h"
#include "control.h"
#include "i18n.h"
#include "sim.h"
#include "save.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

static void check(HeadlessStatus*s,int ok,const char*name){s->checks++;if(!ok){s->failures++;if(!s->first_failure)s->first_failure=name;}}
static void hash_u64(uint64_t*h,uint64_t x){*h^=x;*h*=1099511628211ULL;}
static uint64_t game_digest(const Game*g){uint64_t h=1469598103934665603ULL;hash_u64(&h,g->genome.master);hash_u64(&h,(uint64_t)g->genome.bpm);hash_u64(&h,(uint64_t)g->mode);hash_u64(&h,(uint64_t)g->phrase_index);hash_u64(&h,(uint64_t)g->integrity);hash_u64(&h,(uint64_t)g->recovered);hash_u64(&h,(uint64_t)g->total);hash_u64(&h,(uint64_t)g->node_count);hash_u64(&h,(uint64_t)lroundf(g->player.pos.x*1000));hash_u64(&h,(uint64_t)lroundf(g->player.pos.y*1000));for(int i=0;i<g->node_count;i++){hash_u64(&h,(uint64_t)g->nodes[i].state);hash_u64(&h,(uint64_t)g->nodes[i].phrase<<8|g->nodes[i].step);}return h;}
static uint64_t simulate(const char*seed,GameMode mode,HeadlessStatus*s){Game g;sfbs_game_init(&g,seed,mode);g.freeze_echo=true;uint64_t end=sfbs_tick_sample((uint64_t)SFBS_BARS*4*SFBS_PPQN,g.genome.bpm),sample=0,step=SFBS_RATE/30;unsigned visited=0;int frame=0;
 check(s,sfbs_song_valid(&g.song),"music_schedule_invalid");check(s,g.song.count>0&&g.song.count<=SFBS_EVENTS,"music_event_capacity");check(s,g.total>0,"recovery_denominator");check(s,g.phrases[0].start_bar==0&&g.phrases[SFBS_PHRASES-1].start_bar==52,"phrase_plan");check(s,end>=SFBS_RATE*120ULL&&end<=SFBS_RATE*161ULL,"run_duration");
 int stem_mask=0;for(int i=0;i<g.song.count;i++)stem_mask|=1<<g.song.events[i].stem;check(s,(stem_mask&15)==15,"required_stems");
 while(sample<=end){float a=frame*.017f+(float)mode;V2 input={cosf(a),sinf(a*.73f)};bool pulse=(frame%19)==0;sfbs_game_step(&g,1.0f/30,input,pulse,sample);if(g.phrase_index>=0&&g.phrase_index<SFBS_PHRASES)visited|=1u<<g.phrase_index;sample+=step;frame++;}
 sfbs_game_step(&g,1.0f/30,(V2){0,0},false,end+SFBS_RATE);check(s,g.ended&&g.won,"complete_56_bar_loop");check(s,visited==((1u<<SFBS_PHRASES)-1),"all_phrases_visited");check(s,g.echo_active,"echo_activation");check(s,g.node_count<=SFBS_MAX_NODES,"node_capacity");check(s,sfbs_recovery(&g)>=0&&sfbs_recovery(&g)<=100,"recovery_range");check(s,sfbs_len(g.player.pos)<=300.01f,"arena_boundary");return game_digest(&g);}
HeadlessStatus sfbs_headless_verify(void){HeadlessStatus s={0};const char*seeds[3]={"BAD234","FLOW77","PULSE9"};s.digest=1469598103934665603ULL;for(int m=0;m<3;m++){int before=s.failures;Game a,b;sfbs_game_init(&a,seeds[m],(GameMode)m);sfbs_game_init(&b,seeds[m],(GameMode)m);check(&s,!memcmp(&a.genome,&b.genome,sizeof a.genome),"genome_determinism");check(&s,!memcmp(a.phrases,b.phrases,sizeof a.phrases),"phrase_determinism");check(&s,a.song.count==b.song.count&&!memcmp(a.song.events,b.song.events,(size_t)a.song.count*sizeof a.song.events[0]),"music_determinism");uint64_t da=simulate(seeds[m],(GameMode)m,&s),db=simulate(seeds[m],(GameMode)m,&s);check(&s,da==db,"simulation_determinism");if(da==db)s.deterministic_pairs++;if(s.failures==before)s.modes_completed++;hash_u64(&s.digest,da);s.seeds_checked++;}
 Game damage;sfbs_game_init(&damage,"DAMAGE",MODE_FLOW);int integrity=damage.integrity;sfbs_force_damage(&damage);check(&s,damage.integrity==integrity-1&&damage.player.invuln>0,"flow_damage");Game bloom;sfbs_game_init(&bloom,"BLOOM7",MODE_BLOOM);sfbs_force_damage(&bloom);check(&s,!bloom.ended&&bloom.integrity==99,"bloom_no_failure");Game pulse;sfbs_game_init(&pulse,"PULSE9",MODE_PULSE);check(&s,pulse.integrity==2&&pulse.echo_delay==6&&pulse.echo_width>15,"pulse_pressure");float off=sfbs_resonance(.5f,96,.11f),on=sfbs_resonance(0,96,.11f);check(&s,on>off&&on>.99f,"continuous_beat_resonance");for(int l=0;l<LANG_COUNT;l++)for(int id=0;id<TXT_COUNT;id++)check(&s,sfbs_text((Language)l,(TextId)id)[0]!=0,"i18n_completeness");SaveData save;sfbs_save_defaults(&save);check(&s,sfbs_save_valid(&save)&&save.first_person==0,"persistent_defaults");ControlStatus control=sfbs_control_verify();s.control_checks=control.checks;s.control_failures=control.failures;s.control_transitions=control.transitions_tested;check(&s,control.failures==0,"control_harness");hash_u64(&s.digest,control.digest);return s;}
void sfbs_status_json(const HeadlessStatus*s){printf("{\"schema_version\":1,\"build\":{\"state\":\"passed\",\"language\":\"C99\",\"headless\":true},\"tests\":{\"state\":\"%s\",\"checks\":%d,\"failures\":%d,\"first_failure\":",s->failures?"failed":"passed",s->checks,s->failures);if(s->first_failure)printf("\"%s\"",s->first_failure);else printf("null");printf(",\"seeds_checked\":%d,\"deterministic_pairs\":%d,\"modes_completed\":%d,\"bars_per_run\":56,\"control_checks\":%d,\"control_failures\":%d,\"control_transitions\":%d,\"digest\":\"%016llx\"},\"features\":{\"deterministic_seed\":true,\"euclidean_patterns\":true,\"runtime_synthesis\":true,\"sample_transport\":true,\"bloom_flow_pulse\":true,\"delayed_path_echo\":true,\"recovery_and_integrity\":true,\"headless_control_harness\":true,\"first_person_3d\":true,\"overview_3d\":true,\"i18n_menus\":true,\"persistence\":true,\"release_size_gate\":true},\"compliance\":{\"mechanical_headless\":%s,\"rendering_requires_device_review\":true,\"windows_release_requires_target_review\":true},\"ready\":%s}\n",s->seeds_checked,s->deterministic_pairs,s->modes_completed,s->control_checks,s->control_failures,s->control_transitions,(unsigned long long)s->digest,s->failures?"false":"true",s->failures?"false":"true");}
