#include "audio.h"
#include "render.h"
#include "save.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <math.h>
typedef enum { ST_BOOT,ST_TITLE,ST_SEED,ST_MODE,ST_PLAY,ST_PAUSE,ST_RESULTS,ST_CREDITS } AppState;
static RenderTexture2D target; static Game game; static AudioEngine audio; static SaveData save; static AppState state=ST_BOOT; static float boot_time; static bool debug,collision,gallery; static char entry[7]; static int entry_len;
static void start(void){sfbs_game_init(&game,save.seed,(GameMode)save.mode);sfbs_audio_restart(&audio,&game.song);state=ST_PLAY;}
static bool confirm(void){return IsKeyPressed(KEY_ENTER)||IsKeyPressed(KEY_SPACE)||IsGamepadButtonPressed(0,GAMEPAD_BUTTON_RIGHT_FACE_DOWN);}
static void screen_begin(void){BeginTextureMode(target);ClearBackground(BLACK);}
static void screen_end(void){EndTextureMode();BeginDrawing();ClearBackground(BLACK);float s=fminf(GetScreenWidth()/640.0f,GetScreenHeight()/360.0f);Rectangle src={0,0,640,-360},dst={(GetScreenWidth()-640*s)/2,(GetScreenHeight()-360*s)/2,640*s,360*s};DrawTexturePro(target.texture,src,dst,(Vector2){0,0},0,WHITE);EndDrawing();}
static void menu_text(const char*sub){Palette p=sfbs_palette(game.genome.palette);sfbs_center_text("SONGS FROM BAD SECTORS",64,28,p.player);sfbs_center_text(sub,112,16,p.active);}
int main(void){SetConfigFlags(FLAG_WINDOW_RESIZABLE|FLAG_VSYNC_HINT);InitWindow(1280,720,"Songs From Bad Sectors");SetTargetFPS(60);target=LoadRenderTexture(640,360);SetTextureFilter(target.texture,TEXTURE_FILTER_POINT);sfbs_save_load("sfbs.sav",&save);sfbs_game_init(&game,save.seed,(GameMode)save.mode);sfbs_audio_open(&audio,&game.song);while(!WindowShouldClose()){
 float dt=GetFrameTime();if(IsKeyPressed(KEY_F1))debug=!debug;if(IsKeyPressed(KEY_F2))collision=!collision;if(IsKeyPressed(KEY_F3))game.freeze_echo=!game.freeze_echo;if(IsKeyPressed(KEY_F4))gallery=!gallery;if(IsKeyPressed(KEY_F5)){sfbs_force_damage(&game);sfbs_audio_damage(&audio);}if(IsKeyPressed(KEY_F6)){for(int i=0;i<game.node_count;i++)if(game.nodes[i].state!=NODE_EXPIRED&&game.nodes[i].state!=NODE_RECOVERED){game.nodes[i].state=NODE_RECOVERED;game.recovered+=game.nodes[i].weight;}}if(IsKeyPressed(KEY_F7)){audio.clock+=sfbs_tick_sample(16*SFBS_PPQN,game.genome.bpm);}if(IsKeyPressed(KEY_F8)){sfbs_random_seed((uint64_t)time(0)^audio.clock,save.seed);start();}for(int i=0;i<4;i++)if(IsKeyPressed(KEY_ONE+i))sfbs_audio_stem(&audio,i,audio.stem[i]==0);
 switch(state){case ST_BOOT:boot_time+=dt;if(boot_time>2.6f||confirm())state=ST_TITLE;break;case ST_TITLE:if(confirm())state=ST_MODE;if(IsKeyPressed(KEY_S))state=ST_SEED;if(IsKeyPressed(KEY_C))state=ST_CREDITS;break;case ST_MODE:if(IsKeyPressed(KEY_LEFT)||IsGamepadButtonPressed(0,GAMEPAD_BUTTON_LEFT_FACE_LEFT))save.mode=(save.mode+2)%3;if(IsKeyPressed(KEY_RIGHT)||IsGamepadButtonPressed(0,GAMEPAD_BUTTON_LEFT_FACE_RIGHT))save.mode=(save.mode+1)%3;if(confirm()){sfbs_save_write("sfbs.sav",&save);start();}if(IsKeyPressed(KEY_ESCAPE))state=ST_TITLE;break;case ST_SEED:{int ch=GetCharPressed();while(ch){char tmp[2]={(char)ch,0},norm[7];sfbs_seed_normalize(tmp,norm);if(entry_len<6&&strchr("23456789ABCDEFGHJKMNPQRSTUVWXYZ",norm[0]))entry[entry_len++]=norm[0];ch=GetCharPressed();}entry[entry_len]=0;if(IsKeyPressed(KEY_BACKSPACE)&&entry_len)entry[--entry_len]=0;if(IsKeyPressed(KEY_R)){sfbs_random_seed((uint64_t)time(0)^audio.clock,entry);entry_len=6;}if(confirm()&&entry_len){sfbs_seed_normalize(entry,save.seed);state=ST_MODE;}if(IsKeyPressed(KEY_ESCAPE))state=ST_TITLE;}break;case ST_PLAY:{if(IsKeyPressed(KEY_ESCAPE)||IsKeyPressed(KEY_P)){state=ST_PAUSE;break;}V2 in={(IsKeyDown(KEY_D)||IsKeyDown(KEY_RIGHT))-(IsKeyDown(KEY_A)||IsKeyDown(KEY_LEFT)),(IsKeyDown(KEY_S)||IsKeyDown(KEY_DOWN))-(IsKeyDown(KEY_W)||IsKeyDown(KEY_UP))};if(IsGamepadAvailable(0)){in.x+=GetGamepadAxisMovement(0,GAMEPAD_AXIS_LEFT_X);in.y+=GetGamepadAxisMovement(0,GAMEPAD_AXIS_LEFT_Y);}bool pulse=IsKeyPressed(KEY_SPACE)||IsKeyPressed(KEY_Z)||IsKeyPressed(KEY_ENTER)||IsGamepadButtonPressed(0,GAMEPAD_BUTTON_RIGHT_FACE_DOWN);sfbs_game_step(&game,dt,in,pulse,sfbs_audio_clock(&audio));if(game.ended)state=ST_RESULTS;}break;case ST_PAUSE:if(confirm()||IsKeyPressed(KEY_ESCAPE)||IsKeyPressed(KEY_P))state=ST_PLAY;if(IsKeyPressed(KEY_R))start();break;case ST_RESULTS:if(IsKeyPressed(KEY_R)||confirm())start();if(IsKeyPressed(KEY_N)){sfbs_random_seed((uint64_t)time(0)^audio.clock,save.seed);start();}if(IsKeyPressed(KEY_M))state=ST_MODE;if(IsKeyPressed(KEY_S))state=ST_SEED;if(IsKeyPressed(KEY_ESCAPE))state=ST_TITLE;break;case ST_CREDITS:if(confirm()||IsKeyPressed(KEY_ESCAPE))state=ST_TITLE;break;}
 screen_begin();Palette p=sfbs_palette(game.genome.palette);if(state==ST_PLAY||state==ST_PAUSE||state==ST_RESULTS){sfbs_render_game(&game,sfbs_transport(sfbs_audio_clock(&audio),game.genome.bpm),debug,collision);if(state==ST_PAUSE){DrawRectangle(0,0,640,360,ColorAlpha(BLACK,.65f));sfbs_center_text("READ PAUSED",145,28,p.player);sfbs_center_text("ENTER RESUME   R RESTART",190,13,p.active);}else if(state==ST_RESULTS){DrawRectangle(0,0,640,360,ColorAlpha(p.bg,.78f));sfbs_center_text(game.won?"TRACK RECOVERED":"SIGNAL LOST",80,27,p.player);char x[80];snprintf(x,sizeof x,"%s  /  %s  /  %d%%",game.seed,sfbs_mode_name(game.mode),sfbs_recovery(&game));sfbs_center_text(x,130,18,p.active);sfbs_center_text(sfbs_result_label(sfbs_recovery(&game)),160,14,p.stable);sfbs_center_text("R REPLAY   N NEW   M MODE   S SEED",220,13,p.player);}}else if(state==ST_BOOT){sfbs_center_text("A:\\> READ TRACK01.DAT",120,15,p.stable);sfbs_center_text(boot_time<.8f?"SCANNING...":boot_time<1.7f?"BAD SECTORS DETECTED":"SIGNAL FOUND",155,16,p.active);}else if(state==ST_TITLE){menu_text(save.seed);sfbs_center_text("ENTER PLAY   S SEED   C CREDITS",180,15,p.player);sfbs_center_text("WASD / ARROWS MOVE     SPACE PULSE",250,12,p.stable);}else if(state==ST_MODE){menu_text("SELECT PRESSURE");sfbs_center_text(sfbs_mode_name((GameMode)save.mode),165,30,p.active);sfbs_center_text("LEFT / RIGHT     ENTER BEGIN",225,13,p.player);}else if(state==ST_SEED){menu_text("ENTER SIX-CHARACTER SEED");sfbs_center_text(entry_len?entry:"______",160,34,p.active);sfbs_center_text("R RANDOMIZE     ENTER ACCEPT",225,13,p.player);}else{menu_text("CREDITS");sfbs_center_text("DESIGNED FROM REQ_DESIGN.MD",150,13,p.active);sfbs_center_text("BUILT WITH RAYLIB 6.0 (ZLIB/LICENSE)",178,12,p.stable);sfbs_center_text("SOURCE LICENSE: GPL-3.0",200,12,p.stable);}if(gallery){for(int i=0;i<8;i++){Palette q=sfbs_palette(i);DrawRectangle(10+i*78,310,70,20,q.stable);}}screen_end();}
 sfbs_save_write("sfbs.sav",&save);sfbs_audio_close(&audio);UnloadRenderTexture(target);CloseWindow();return 0;}
