#include "sim.h"
#include <string.h>
#include <math.h>
static float rings[3]={105,190,270};
static int phase_weight(int p){return p>=PH_FINAL?3:p>=PH_FLOW?2:1;}
static void load_phrase(Game*g,int pi){Phrase*p=&g->phrases[pi];for(int i=0;i<g->node_count;i++)if(g->nodes[i].state!=NODE_RECOVERED)g->nodes[i].state=NODE_EXPIRED;
 /* Preserve recent recovered geometry, but always reserve a complete phrase. */
 if(g->node_count+p->pattern.steps>SFBS_MAX_NODES){int keep=SFBS_MAX_NODES-p->pattern.steps,write=0,start=g->node_count-keep;if(start<0)start=0;for(int i=start;i<g->node_count;i++)if(g->nodes[i].state==NODE_RECOVERED&&write<keep)g->nodes[write++]=g->nodes[i];g->node_count=write;}
 for(int i=0;i<p->pattern.steps;i++){float a=2*SFBS_PI*i/p->pattern.steps-SFBS_PI/2;Node*n=&g->nodes[g->node_count++];n->pos=(V2){cosf(a)*rings[p->ring],sinf(a)*rings[p->ring]};n->step=(uint8_t)i;n->state=(p->pattern.bits&(1u<<i))?NODE_DORMANT:NODE_EXPIRED;n->weight=(uint8_t)phase_weight(p->phase);n->phrase=(uint8_t)pi;n->pulse=0;}}
void sfbs_game_init(Game*g,const char*seed,GameMode mode){memset(g,0,sizeof *g);sfbs_seed_normalize(seed,g->seed);g->genome=sfbs_genome(g->seed);g->mode=mode;sfbs_phrases(&g->genome,mode,g->phrases);for(int i=0;i<SFBS_PHRASES;i++)g->total+=g->phrases[i].pattern.pulses*phase_weight(g->phrases[i].phase);sfbs_song_generate(&g->genome,g->phrases,&g->song);g->player.pos=(V2){0,0};g->integrity=mode==MODE_BLOOM?99:mode==MODE_FLOW?3:2;g->echo_width=mode==MODE_BLOOM?10.5f:mode==MODE_PULSE?17.25f:15;g->echo_delay=mode==MODE_BLOOM?10:mode==MODE_FLOW?8:6;load_phrase(g,0);}
void sfbs_path_push(PathBuffer*b,V2 p,uint64_t tick){b->p[b->head]=p;b->tick[b->head]=tick;b->head=(b->head+1)%SFBS_PATH;if(b->count<SFBS_PATH)b->count++;}
bool sfbs_path_at(const PathBuffer*b,uint64_t tick,V2*out){if(!b->count)return false;int best=-1;uint64_t d=~0ULL;for(int k=0;k<b->count;k++){int i=(b->head-1-k+SFBS_PATH)%SFBS_PATH;uint64_t x=b->tick[i]>tick?b->tick[i]-tick:tick-b->tick[i];if(x<d){d=x;best=i;}}if(best<0)return false;*out=b->p[best];return true;}
uint64_t sfbs_echo_head_tick(uint64_t tick,float delay_beats){uint64_t beat=(tick/SFBS_PPQN)*SFBS_PPQN,delay=(uint64_t)(delay_beats*SFBS_PPQN);return beat>delay?beat-delay:0;}
float sfbs_segment_distance(V2 p,V2 a,V2 b){V2 ab={b.x-a.x,b.y-a.y},ap={p.x-a.x,p.y-a.y};float d=ab.x*ab.x+ab.y*ab.y,t=d>0?(ap.x*ab.x+ap.y*ab.y)/d:0;t=sfbs_clampf(t,0,1);return sfbs_len((V2){p.x-(a.x+ab.x*t),p.y-(a.y+ab.y*t)});}
int sfbs_recovery(const Game*g){return g->total?g->recovered*100/g->total:0;}
void sfbs_force_damage(Game*g){if(g->player.invuln>0)return;g->player.invuln=.85f;if(g->mode!=MODE_BLOOM)g->integrity--;for(int i=g->node_count-1;i>=0;i--)if(g->nodes[i].state==NODE_RECOVERED){g->nodes[i].state=NODE_CORRUPTED;g->recovered-=g->nodes[i].weight;break;}if(g->integrity<=0&&g->mode!=MODE_BLOOM){g->ended=true;g->won=false;}}
void sfbs_game_step(Game*g,float dt,V2 input,bool pulse,uint64_t sample){if(g->ended)return;if(dt>.05f)dt=.05f;Transport t=sfbs_transport(sample,g->genome.bpm);int pi=(int)t.bar/4;if(pi>=SFBS_PHRASES){g->ended=true;g->won=true;return;}if(pi!=g->phrase_index){g->phrase_index=pi;load_phrase(g,pi);if(g->mode==MODE_FLOW&&pi>=9)g->echo_delay=6;if(g->mode==MODE_PULSE&&pi>=9)g->echo_delay=4;}
 Player*p=&g->player;p->pulse_cd=fmaxf(0,p->pulse_cd-dt);p->invuln=fmaxf(0,p->invuln-dt);p->glow=fmaxf(0,p->glow-dt*2);float il=sfbs_len(input);if(il>1)input=sfbs_scale(input,1/il);p->vel=sfbs_add(p->vel,sfbs_scale(input,900*dt));float drag=expf(-3.2f*dt);p->vel=sfbs_scale(p->vel,drag);float max=g->mode==MODE_PULSE?265:240,l=sfbs_len(p->vel);if(l>max)p->vel=sfbs_scale(p->vel,max/l);if(pulse&&p->pulse_cd<=0){V2 d=il>.05f?sfbs_norm(input):sfbs_norm(p->vel);float r=sfbs_resonance(t.beat_phase,g->genome.bpm,g->mode==MODE_BLOOM?.14f:.11f);p->vel=sfbs_add(p->vel,sfbs_scale(d,(g->mode==MODE_BLOOM?165:150)+r*(g->mode==MODE_PULSE?105:90)));p->pulse_cd=g->mode==MODE_PULSE?.58f:.65f;p->invuln=fmaxf(p->invuln,.12f);p->glow=1;}
 p->pos=sfbs_add(p->pos,sfbs_scale(p->vel,dt));l=sfbs_len(p->pos);if(l>276){V2 n=sfbs_norm(p->pos);p->vel=sfbs_add(p->vel,sfbs_scale(n,-(l-276)*12*dt));if(l>296)p->pos=sfbs_scale(n,296);}
 uint64_t tick=(sample*(uint64_t)g->genome.bpm*SFBS_PPQN)/((uint64_t)SFBS_RATE*60);uint64_t sub=tick/(SFBS_PPQN/4);if(sub!=g->last_path_tick){sfbs_path_push(&g->path,p->pos,tick);g->last_path_tick=sub;}
 Phrase*ph=&g->phrases[pi];int current=(int)(t.bar_phase*ph->pattern.steps)%ph->pattern.steps,phrase_bar=(int)t.bar-ph->start_bar,next=(current+1)%ph->pattern.steps;for(int i=0;i<g->node_count;i++){Node*n=&g->nodes[i];if(n->phrase!=pi)continue;if(n->state==NODE_DORMANT&&n->step==next)n->state=NODE_TELEGRAPHING;if((n->state==NODE_DORMANT||n->state==NODE_TELEGRAPHING)&&(phrase_bar>0||n->step<=current))n->state=NODE_AVAILABLE;if(n->state==NODE_AVAILABLE||n->state==NODE_CORRUPTED){float distance=sfbs_len((V2){n->pos.x-p->pos.x,n->pos.y-p->pos.y});if(distance<82)n->pulse=sfbs_clampf(n->pulse+dt*(1.25f+2.25f*(1-distance/82)),0,1);else n->pulse=sfbs_clampf(n->pulse-dt*2,0,1);float reach=(p->glow>0?42:16)+n->pulse*28;if(distance<reach||n->pulse>=.995f){n->state=NODE_RECOVERED;n->pulse=1;g->recovered+=n->weight;}}}
 uint64_t beat=tick/SFBS_PPQN;if(beat!=g->last_beat){g->last_beat=beat;if(pi>=3)g->echo_active=true;}if(g->echo_active&&!g->freeze_echo&&p->invuln<=0){uint64_t head=sfbs_echo_head_tick(tick,g->echo_delay),persist=4*SFBS_PPQN;V2 previous={0};bool have=false;float nearest=100000;for(int k=0;k<g->path.count;k++){int j=(g->path.head-1-k+SFBS_PATH)%SFBS_PATH;uint64_t pt=g->path.tick[j];if(pt>head)continue;if(head-pt>persist)break;if(have)nearest=fminf(nearest,sfbs_segment_distance(p->pos,g->path.p[j],previous));previous=g->path.p[j];have=true;}if(nearest<g->echo_width+8){sfbs_force_damage(g);p->vel=sfbs_scale(sfbs_norm((V2){p->pos.x-previous.x,p->pos.y-previous.y}),180);}}}
